### ISSUE TITLE
Setup Guide?

### ISSUE THREAD

**Issue by jckefan** [cTxplorer/xirr-calculator#3]
Please provide a setup guide.

**Comment by cTxplorer** [comment]
Hey @jckefan, this is a Next.js app.

To setup locally,
1. Install node modules - `yarn install`
2. Run local server - `yarn dev`

Note - the XIRR calculation for Zerodha is not accurate, due to multiple reasons. Now that Zerodha has started showing portfolio & stock-level XIRR ([ref](https://support.zerodha.com/category/console/portfolio/holdings/articles/portfolio-xirr)), I will add a banner on homepage to recommend that feature.
